CREATE USER 'sistema'@'localhost' IDENTIFIED BY 'sistema1234';
GRANT ALL PRIVILEGES ON * . * TO 'sistema'@'localhost';
FLUSH PRIVILEGES;

CREATE DATABASE CursoPHP
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

COMMIT;

use CursoPHP;

CREATE TABLE IF NOT EXISTS clientes (
id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(256) NOT NULL,
telefone VARCHAR(11),
nascimento DATE NOT NULL,
dataCadastro DATETIME,
PRIMARY KEY(id)
)DEFAULT CHARSET = utf8;